FALCON-2121 If a feed does not exist on a cluster, process submission throws NPE
After the change:
`bin/falcon entity -submit -type process -file examples/entity/filesystem/pig-process.xml
ERROR: Bad Request;default/Feed in does not exist on cluster local2`

Author: Pallavi Rao <pallavi.rao@inmobi.com>

Reviewers: @sandeepSamudrala

Closes #270 from pallavi-rao/2121 and squashes the following commits:

ed3a8f4 [Pallavi Rao] Addressed review comment
0884518 [Pallavi Rao] FALCON-2121 Removing static import
60d1e00 [Pallavi Rao] FALCON-2121 If a feed does not exist on a cluster, process submission fails with NPE