FALCON-1782 Client returns FalconWebException instead of the expected…
testing :

$ bin/falcon entity -type process -name process1 -properties falcon.scheduler:native -schedule
ERROR: Bad Request;default/Entity process1 is already scheduled on configured workflow engine.

Author: Praveen Adlakha <adlakha.praveen@gmail.com>

Reviewers: Ajay Yadava<ajayyadava@apache.org>, Sandeep Samudrala <sandysmdl@gmail.com>

Closes #18 from PraveenAdlakha/FALCON-1782